// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from '@hey-api/client-fetch';

import { client } from './client.gen';
import type { GetContent20Data, GetContent20Errors, GetContent20Responses, GetContentItemById20Data, GetContentItemById20Errors, GetContentItemById20Responses, GetContentItemByPath20Data, GetContentItemByPath20Errors, GetContentItemByPath20Responses, GetContentItems20Data, GetContentItems20Errors, GetContentItems20Responses, GetMedia20Data, GetMedia20Errors, GetMedia20Responses, GetMediaItemById20Data, GetMediaItemById20Errors, GetMediaItemById20Responses, GetMediaItemByPath20Data, GetMediaItemByPath20Errors, GetMediaItemByPath20Responses, GetMediaItems20Data, GetMediaItems20Responses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class ContentService {
    public static getContent20<ThrowOnError extends boolean = true>(options?: Options<GetContent20Data, ThrowOnError>): RequestResult<GetContent20Responses, GetContent20Errors, ThrowOnError> {
        return (options?.client ?? client).get<GetContent20Responses, GetContent20Errors, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/content',
            ...options
        });
    }
    
    public static getContentItemById20<ThrowOnError extends boolean = true>(options: Options<GetContentItemById20Data, ThrowOnError>): RequestResult<GetContentItemById20Responses, GetContentItemById20Errors, ThrowOnError> {
        return (options.client ?? client).get<GetContentItemById20Responses, GetContentItemById20Errors, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/content/item/{id}',
            ...options
        });
    }
    
    public static getContentItemByPath20<ThrowOnError extends boolean = true>(options: Options<GetContentItemByPath20Data, ThrowOnError>): RequestResult<GetContentItemByPath20Responses, GetContentItemByPath20Errors, ThrowOnError> {
        return (options.client ?? client).get<GetContentItemByPath20Responses, GetContentItemByPath20Errors, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/content/item/{path}',
            ...options
        });
    }
    
    public static getContentItems20<ThrowOnError extends boolean = true>(options?: Options<GetContentItems20Data, ThrowOnError>): RequestResult<GetContentItems20Responses, GetContentItems20Errors, ThrowOnError> {
        return (options?.client ?? client).get<GetContentItems20Responses, GetContentItems20Errors, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/content/items',
            ...options
        });
    }
}

export class MediaService {
    public static getMedia20<ThrowOnError extends boolean = true>(options?: Options<GetMedia20Data, ThrowOnError>): RequestResult<GetMedia20Responses, GetMedia20Errors, ThrowOnError> {
        return (options?.client ?? client).get<GetMedia20Responses, GetMedia20Errors, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/media',
            ...options
        });
    }
    
    public static getMediaItemById20<ThrowOnError extends boolean = true>(options: Options<GetMediaItemById20Data, ThrowOnError>): RequestResult<GetMediaItemById20Responses, GetMediaItemById20Errors, ThrowOnError> {
        return (options.client ?? client).get<GetMediaItemById20Responses, GetMediaItemById20Errors, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/media/item/{id}',
            ...options
        });
    }
    
    public static getMediaItemByPath20<ThrowOnError extends boolean = true>(options: Options<GetMediaItemByPath20Data, ThrowOnError>): RequestResult<GetMediaItemByPath20Responses, GetMediaItemByPath20Errors, ThrowOnError> {
        return (options.client ?? client).get<GetMediaItemByPath20Responses, GetMediaItemByPath20Errors, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/media/item/{path}',
            ...options
        });
    }
    
    public static getMediaItems20<ThrowOnError extends boolean = true>(options?: Options<GetMediaItems20Data, ThrowOnError>): RequestResult<GetMediaItems20Responses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<GetMediaItems20Responses, unknown, ThrowOnError>({
            security: [{ name: 'Api-Key', type: 'apiKey' }],
            url: '/umbraco/delivery/api/v2/media/items',
            ...options
        });
    }
}
