// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from '@hey-api/client-fetch';

import { client } from './client.gen';
import type { ByIdV202Data, ByIdV202Errors, ByIdV202Responses, ByIdV20Data, ByIdV20Errors, ByIdV20Responses, ByPathV20Data, ByPathV20Errors, ByPathV20Responses, ByRouteV20Data, ByRouteV20Errors, ByRouteV20Responses, ItemsV202Data, ItemsV202Responses, ItemsV20Data, ItemsV20Errors, ItemsV20Responses, QueryV202Data, QueryV202Errors, QueryV202Responses, QueryV20Data, QueryV20Errors, QueryV20Responses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class ContentService {
    public static queryV20<ThrowOnError extends boolean = true>(options?: Options<QueryV20Data, ThrowOnError>): RequestResult<QueryV20Responses, QueryV20Errors, ThrowOnError> {
        return (options?.client ?? client).get<QueryV20Responses, QueryV20Errors, ThrowOnError>({ url: '/umbraco/delivery/api/v2/content', ...options });
    }
    
    public static byRouteV20<ThrowOnError extends boolean = true>(options: Options<ByRouteV20Data, ThrowOnError>): RequestResult<ByRouteV20Responses, ByRouteV20Errors, ThrowOnError> {
        return (options.client ?? client).get<ByRouteV20Responses, ByRouteV20Errors, ThrowOnError>({ url: '/umbraco/delivery/api/v2/content/item/{path}', ...options });
    }
    
    public static byIdV20<ThrowOnError extends boolean = true>(options: Options<ByIdV20Data, ThrowOnError>): RequestResult<ByIdV20Responses, ByIdV20Errors, ThrowOnError> {
        return (options.client ?? client).get<ByIdV20Responses, ByIdV20Errors, ThrowOnError>({ url: '/umbraco/delivery/api/v2/content/item/{id}', ...options });
    }
    
    public static itemsV20<ThrowOnError extends boolean = true>(options?: Options<ItemsV20Data, ThrowOnError>): RequestResult<ItemsV20Responses, ItemsV20Errors, ThrowOnError> {
        return (options?.client ?? client).get<ItemsV20Responses, ItemsV20Errors, ThrowOnError>({ url: '/umbraco/delivery/api/v2/content/items', ...options });
    }
}

export class MediaService {
    public static queryV20<ThrowOnError extends boolean = true>(options?: Options<QueryV202Data, ThrowOnError>): RequestResult<QueryV202Responses, QueryV202Errors, ThrowOnError> {
        return (options?.client ?? client).get<QueryV202Responses, QueryV202Errors, ThrowOnError>({ url: '/umbraco/delivery/api/v2/media', ...options });
    }
    
    public static byPathV20<ThrowOnError extends boolean = true>(options: Options<ByPathV20Data, ThrowOnError>): RequestResult<ByPathV20Responses, ByPathV20Errors, ThrowOnError> {
        return (options.client ?? client).get<ByPathV20Responses, ByPathV20Errors, ThrowOnError>({ url: '/umbraco/delivery/api/v2/media/item/{path}', ...options });
    }
    
    public static byIdV20<ThrowOnError extends boolean = true>(options: Options<ByIdV202Data, ThrowOnError>): RequestResult<ByIdV202Responses, ByIdV202Errors, ThrowOnError> {
        return (options.client ?? client).get<ByIdV202Responses, ByIdV202Errors, ThrowOnError>({ url: '/umbraco/delivery/api/v2/media/item/{id}', ...options });
    }
    
    public static itemsV20<ThrowOnError extends boolean = true>(options?: Options<ItemsV202Data, ThrowOnError>): RequestResult<ItemsV202Responses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<ItemsV202Responses, unknown, ThrowOnError>({ url: '/umbraco/delivery/api/v2/media/items', ...options });
    }
}
