// This file is auto-generated by @hey-api/openapi-ts

export type ApiBlockGridAreaModel = {
    alias: string;
    rowSpan: number;
    columnSpan: number;
    items: Array<ApiBlockGridItemModel>;
};

export type ApiBlockGridItemModel = ApiBlockItemModel & {
    rowSpan?: number;
    columnSpan?: number;
    areaGridColumns?: number;
    areas?: Array<ApiBlockGridAreaModel>;
};

export type ApiBlockGridModel = {
    gridColumns: number;
    items: Array<ApiBlockGridItemModel>;
};

export type ApiBlockItemModel = {
    content: IApiElementModel;
    settings?: IApiElementModel;
};

export type ApiBlockListModel = {
    items: Array<(ApiBlockItemModel | ApiBlockGridItemModel)>;
};

export type ApiContentRouteModel = {
    path: string;
    startItem: (ApiContentStartItemModel);
};

export type ApiContentStartItemModel = {
    id: string;
    path: string;
};

export type ApiLinkModel = {
    readonly url?: (string) | null;
    readonly queryString?: (string) | null;
    readonly title?: (string) | null;
    readonly target?: (string) | null;
    readonly destinationId?: (string) | null;
    readonly destinationType?: (string) | null;
    readonly route?: ((ApiContentRouteModel) | null);
    linkType: LinkTypeModel;
};

export type BlogPostContentModel = IApiContentModelBase & {
    properties?: BlogPostPropertiesModel;
};

export type BlogPostContentResponseModel = IApiContentResponseModelBase & BlogPostContentModel;

export type BlogPostPropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel & {
    publishedDate?: (string) | null;
};

export type BlogsPageContentModel = IApiContentModelBase & {
    properties?: BlogsPagePropertiesModel;
};

export type BlogsPageContentResponseModel = IApiContentResponseModelBase & BlogsPageContentModel;

export type BlogsPagePropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel;

export type ContentPageContentModel = IApiContentModelBase & {
    properties?: ContentPagePropertiesModel;
};

export type ContentPageContentResponseModel = IApiContentResponseModelBase & ContentPageContentModel;

export type ContentPagePropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel;

export type CVentryElementModel = IApiElementModelBase & {
    properties?: CVentryPropertiesModel;
};

export type CVentryPropertiesModel = {
    employerName?: (string) | null;
    startDate?: (string) | null;
    endDate?: (string) | null;
    jobDescription?: (string) | null;
};

export type EmploymentHistoryElementModel = IApiElementModelBase & {
    properties?: EmploymentHistoryPropertiesModel;
};

export type EmploymentHistoryPropertiesModel = {
    history?: ApiBlockListModel;
};

export type EventInfoElementModel = IApiElementModelBase & {
    properties?: EventInfoPropertiesModel;
};

export type EventInfoPropertiesModel = {
    eventName?: (string) | null;
    eventDate?: (string) | null;
    eventUrl?: (string) | null;
};

export type HomePageContentModel = IApiContentModelBase & {
    properties?: HomePagePropertiesModel;
};

export type HomePageContentResponseModel = IApiContentResponseModelBase & HomePageContentModel;

export type HomePagePropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel;

export type HttpValidationProblemDetails = ProblemDetails & {
    errors?: {
        [key: string]: Array<(string)>;
    };
    [key: string]: (unknown | string) | undefined;
};

export type IApiContentModel = ContentPageContentModel | HomePageContentModel | SpeakingPageContentModel | BlogPostContentModel | SpeakingPostContentModel | BlogsPageContentModel | ProjectsPageContentModel | ProjectPostContentModel;

export type IApiContentModelBase = IApiElementModelBase & {
    readonly id: string;
    readonly contentType: string;
    readonly name?: (string) | null;
    readonly createDate: string;
    readonly updateDate: string;
    readonly route: (ApiContentRouteModel);
};

export type IApiContentResponseModel = ContentPageContentResponseModel | HomePageContentResponseModel | SpeakingPageContentResponseModel | BlogPostContentResponseModel | SpeakingPostContentResponseModel | BlogsPageContentResponseModel | ProjectsPageContentResponseModel | ProjectPostContentResponseModel;

export type IApiContentResponseModelBase = IApiContentModelBase & {
    readonly id: string;
    readonly contentType: string;
    readonly name?: (string) | null;
    readonly createDate: string;
    readonly updateDate: string;
    readonly route: (ApiContentRouteModel);
    readonly cultures: {
        [key: string]: (ApiContentRouteModel);
    };
};

export type IApiElementModel = PageSettingsElementModel | PageContentElementModel | UpdateAlertElementModel | CVentryElementModel | YouTubeVideoElementModel | EventInfoElementModel | ImageWithCaptionElementModel | RichTextElementModel | EmploymentHistoryElementModel | ImageGalleryElementModel;

export type IApiElementModelBase = {
    readonly id: string;
    readonly contentType: string;
};

export type IApiMediaWithCropsModel = {
    readonly id: string;
    readonly name: string;
    readonly mediaType: string;
    readonly url: string;
    readonly extension?: (string) | null;
    readonly width?: (number) | null;
    readonly height?: (number) | null;
    readonly bytes?: (number) | null;
    readonly properties: {
        [key: string]: unknown;
    };
    focalPoint?: ImageFocalPointModel;
    readonly crops?: Array<ImageCropModel> | null;
};

export type IApiMediaWithCropsResponseModel = {
    readonly id: string;
    readonly name: string;
    readonly mediaType: string;
    readonly url: string;
    readonly extension?: (string) | null;
    readonly width?: (number) | null;
    readonly height?: (number) | null;
    readonly bytes?: (number) | null;
    readonly properties: {
        [key: string]: unknown;
    };
    focalPoint: ImageFocalPointModel;
    readonly crops?: Array<ImageCropModel> | null;
    readonly path: string;
    readonly createDate: string;
    readonly updateDate: string;
};

export type ImageCropCoordinatesModel = {
    x1: number;
    y1: number;
    x2: number;
    y2: number;
};

export type ImageCropModel = {
    alias?: (string) | null;
    width: number;
    height: number;
    coordinates?: ImageCropCoordinatesModel;
};

export type ImageFocalPointModel = {
    left: number;
    top: number;
};

export type ImageGalleryElementModel = IApiElementModelBase & {
    properties?: ImageGalleryPropertiesModel;
};

export type ImageGalleryPropertiesModel = {
    gallery?: ApiBlockListModel;
};

export type ImageWithCaptionElementModel = IApiElementModelBase & {
    properties?: ImageWithCaptionPropertiesModel;
};

export type ImageWithCaptionPropertiesModel = {
    image?: Array<IApiMediaWithCropsModel> | null;
    caption?: (string) | null;
};

export enum LinkTypeModel {
    CONTENT = 'Content',
    MEDIA = 'Media',
    EXTERNAL = 'External'
}

export type PageContentElementModel = IApiElementModelBase & {
    properties?: PageContentPropertiesModel;
};

export type PageContentPropertiesModel = {
    featuredImage?: Array<IApiMediaWithCropsModel> | null;
    title?: (string) | null;
    content?: (string) | null;
    grid?: ApiBlockGridModel;
};

export type PagedIApiContentResponseModel = {
    total: number;
    items: Array<IApiContentResponseModel>;
};

export type PagedIApiMediaWithCropsResponseModel = {
    total: number;
    items: Array<IApiMediaWithCropsResponseModel>;
};

export type PageSettingsElementModel = IApiElementModelBase & {
    properties?: PageSettingsPropertiesModel;
};

export type PageSettingsPropertiesModel = {
    umbracoUrlName?: (string) | null;
    umbracoUrlAlias?: (string) | null;
};

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type ProjectPostContentModel = IApiContentModelBase & {
    properties?: ProjectPostPropertiesModel;
};

export type ProjectPostContentResponseModel = IApiContentResponseModelBase & ProjectPostContentModel;

export type ProjectPostPropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel & {
    gitHubUrl?: Array<ApiLinkModel> | null;
    nuGetUrl?: Array<ApiLinkModel> | null;
};

export type ProjectsPageContentModel = IApiContentModelBase & {
    properties?: ProjectsPagePropertiesModel;
};

export type ProjectsPageContentResponseModel = IApiContentResponseModelBase & ProjectsPageContentModel;

export type ProjectsPagePropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel;

export type RichTextElementModel = IApiElementModelBase & {
    properties?: RichTextPropertiesModel;
};

export type RichTextPropertiesModel = {
    content?: (string) | null;
};

export type SpeakingPageContentModel = IApiContentModelBase & {
    properties?: SpeakingPagePropertiesModel;
};

export type SpeakingPageContentResponseModel = IApiContentResponseModelBase & SpeakingPageContentModel;

export type SpeakingPagePropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel;

export type SpeakingPostContentModel = IApiContentModelBase & {
    properties?: SpeakingPostPropertiesModel;
};

export type SpeakingPostContentResponseModel = IApiContentResponseModelBase & SpeakingPostContentModel;

export type SpeakingPostPropertiesModel = PageSettingsPropertiesModel & PageContentPropertiesModel & EventInfoPropertiesModel & {
    additionalEvents?: ApiBlockListModel;
};

export type UpdateAlertElementModel = IApiElementModelBase & {
    properties?: UpdateAlertPropertiesModel;
};

export type UpdateAlertPropertiesModel = {
    date?: (string) | null;
    content?: (string) | null;
};

export type YouTubeVideoElementModel = IApiElementModelBase & {
    properties?: YouTubeVideoPropertiesModel;
};

export type YouTubeVideoPropertiesModel = {
    videoID?: (string) | null;
};

export type QueryV20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * Defines the segment to return. Use this when querying segment variant content items.
     */
    acceptSegment?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fetch?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    /**
     * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    filter?: Array<(string)>;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * Specifies the number of found content items to skip. Use this to control pagination of the response.
     */
    skip?: number;
    /**
     * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    sort?: Array<(string)>;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
    /**
     * Specifies the number of found content items to take. Use this to control pagination of the response.
     */
    take?: number;
};

export type QueryV20Response = (PagedIApiContentResponseModel);

export type ByRouteV20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * Defines the segment to return. Use this when querying segment variant content items.
     */
    acceptSegment?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    path: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type ByRouteV20Response = (IApiContentResponseModel);

export type ByIdV20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * Defines the segment to return. Use this when querying segment variant content items.
     */
    acceptSegment?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    id: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type ByIdV20Response = (IApiContentResponseModel);

export type ItemsV20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * Defines the segment to return. Use this when querying segment variant content items.
     */
    acceptSegment?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    id?: Array<(string)>;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type ItemsV20Response = (Array<IApiContentResponseModel>);

export type ByPathV20Data = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    path: string;
};

export type ByPathV20Response = (IApiMediaWithCropsResponseModel);