// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiBlockGridAreaModel = {
    alias: string;
    rowSpan: number;
    columnSpan: number;
    items: Array<ApiBlockGridItemModel>;
};

export type ApiBlockGridItemModel = {
    rowSpan: number;
    columnSpan: number;
    areaGridColumns: number;
    areas: Array<ApiBlockGridAreaModel>;
    content: IApiElementModel;
    settings: IApiElementModel;
};

export type ApiBlockGridModel = {
    gridColumns: number;
    items: Array<ApiBlockGridItemModel>;
};

export type ApiBlockItemModel = {
    content: IApiElementModel;
    settings: IApiElementModel;
};

export type ApiBlockListModel = {
    items: Array<ApiBlockItemModel>;
};

export type ApiImageCropperValueModel = {
    url: string;
    focalPoint: ImageFocalPointModel;
    crops: null | Array<ImageCropModel>;
};

export type ApiLinkModel = {
    url?: null | string;
    queryString?: null | string;
    title?: null | string;
    target?: null | string;
    destinationId?: null | string;
    destinationType?: null | string;
    route?: IApiContentRouteModel;
    linkType: LinkTypeModel;
    culture?: null | string;
};

export type BlogPostContentModel = IApiContentBaseModel & {
    contentType: 'blogPost';
    properties?: BlogPostContentPropertiesModel;
};

export type BlogPostContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel & {
    publishedDate?: null | string;
};

export type BlogPostContentResponseModel = IApiContentResponseBaseModel & BlogPostContentModel;

export type BlogsPageContentModel = IApiContentBaseModel & {
    contentType: 'blogsPage';
    properties?: BlogsPageContentPropertiesModel;
};

export type BlogsPageContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel;

export type BlogsPageContentResponseModel = IApiContentResponseBaseModel & BlogsPageContentModel;

export type ContentPageContentModel = IApiContentBaseModel & {
    contentType: 'contentPage';
    properties?: ContentPageContentPropertiesModel;
};

export type ContentPageContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel & {
    portrait?: null | Array<IApiMediaWithCropsModel>;
};

export type ContentPageContentResponseModel = IApiContentResponseBaseModel & ContentPageContentModel;

export type CvEntryElementModel = IApiElementBaseModel & {
    contentType: 'cVEntry';
    properties?: CvEntryElementPropertiesModel;
};

export type CvEntryElementPropertiesModel = {
    employerName?: null | string;
    startDate?: null | string;
    endDate?: null | string;
    jobDescription?: null | string;
};

export type EmploymentHistoryElementModel = IApiElementBaseModel & {
    contentType: 'employmentHistory';
    properties?: EmploymentHistoryElementPropertiesModel;
};

export type EmploymentHistoryElementPropertiesModel = {
    history?: ApiBlockListModel | null;
};

export type EventInfoElementModel = IApiElementBaseModel & {
    contentType: 'eventInfo';
    properties?: EventInfoElementPropertiesModel;
};

export type EventInfoElementPropertiesModel = {
    eventName?: null | string;
    eventDate?: null | string;
    eventUrl?: null | string;
};

export type FileMediaPropertiesModel = {
    umbracoFile?: null | string;
    umbracoExtension?: null | string;
    umbracoBytes?: null | number;
};

export type FileMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
    mediaType: 'File';
    properties?: FileMediaPropertiesModel;
};

export type FileMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & FileMediaWithCropsModel;

export type FolderMediaPropertiesModel = {
    [key: string]: unknown;
};

export type FolderMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
    mediaType: 'Folder';
    properties?: FolderMediaPropertiesModel;
};

export type FolderMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & FolderMediaWithCropsModel;

export type HomePageContentModel = IApiContentBaseModel & {
    contentType: 'homePage';
    properties?: HomePageContentPropertiesModel;
};

export type HomePageContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel & {
    siteTitle?: null | string;
    siteTitleMobile?: null | string;
    siteDescription?: null | string;
};

export type HomePageContentResponseModel = IApiContentResponseBaseModel & HomePageContentModel;

export type IApiContentBaseModel = {
    contentType: null | string;
    name?: null | string;
    createDate: string;
    updateDate: string;
    route: IApiContentRouteModel;
    id: string;
    properties: null | {
        [key: string]: unknown;
    };
};

export type IApiContentModel = ({
    contentType: 'contentPage';
} & ContentPageContentModel) | ({
    contentType: 'homePage';
} & HomePageContentModel) | ({
    contentType: 'speakingPage';
} & SpeakingPageContentModel) | ({
    contentType: 'nowPage';
} & NowPageContentModel) | ({
    contentType: 'projectPost';
} & ProjectPostContentModel) | ({
    contentType: 'blogPost';
} & BlogPostContentModel) | ({
    contentType: 'projectsPage';
} & ProjectsPageContentModel) | ({
    contentType: 'speakingPost';
} & SpeakingPostContentModel) | ({
    contentType: 'blogsPage';
} & BlogsPageContentModel);

export type IApiContentResponseBaseModel = {
    contentType: null | string;
    name?: null | string;
    createDate: string;
    updateDate: string;
    route: IApiContentRouteModel;
    id: string;
    properties: null | {
        [key: string]: unknown;
    };
    cultures: null | {
        [key: string]: {
            path: null | string;
            queryString?: null | string;
            startItem: {
                id: string;
                path: null | string;
            };
        };
    };
};

export type IApiContentResponseModel = ({
    contentType: 'contentPage';
} & ContentPageContentResponseModel) | ({
    contentType: 'homePage';
} & HomePageContentResponseModel) | ({
    contentType: 'speakingPage';
} & SpeakingPageContentResponseModel) | ({
    contentType: 'nowPage';
} & NowPageContentResponseModel) | ({
    contentType: 'projectPost';
} & ProjectPostContentResponseModel) | ({
    contentType: 'blogPost';
} & BlogPostContentResponseModel) | ({
    contentType: 'projectsPage';
} & ProjectsPageContentResponseModel) | ({
    contentType: 'speakingPost';
} & SpeakingPostContentResponseModel) | ({
    contentType: 'blogsPage';
} & BlogsPageContentResponseModel);

export type IApiContentRouteModel = {
    path: null | string;
    queryString?: null | string;
    startItem: IApiContentStartItemModel;
};

export type IApiContentStartItemModel = {
    id: string;
    path: null | string;
};

export type IApiElementBaseModel = {
    contentType: null | string;
    id: string;
    name?: null | string;
    properties: null | {
        [key: string]: unknown;
    };
};

export type IApiElementModel = ({
    contentType: 'pageSettings';
} & PageSettingsElementModel) | ({
    contentType: 'pageContent';
} & PageContentElementModel) | ({
    contentType: 'updateAlert';
} & UpdateAlertElementModel) | ({
    contentType: 'cVEntry';
} & CvEntryElementModel) | ({
    contentType: 'youTubeVideo';
} & YouTubeVideoElementModel) | ({
    contentType: 'imageGallery';
} & ImageGalleryElementModel) | ({
    contentType: 'eventInfo';
} & EventInfoElementModel) | ({
    contentType: 'imageWithCaption';
} & ImageWithCaptionElementModel) | ({
    contentType: 'richText';
} & RichTextElementModel) | ({
    contentType: 'employmentHistory';
} & EmploymentHistoryElementModel);

export type IApiMediaWithCropsBaseModel = {
    focalPoint?: ImageFocalPointModel;
    crops?: null | Array<ImageCropModel>;
    id: string;
    name: null | string;
    mediaType: null | string;
    url: null | string;
    extension?: null | string;
    width?: null | number;
    height?: null | number;
    bytes?: null | number;
    properties: null | {
        [key: string]: unknown;
    };
};

export type IApiMediaWithCropsModel = ({
    mediaType: 'Folder';
} & FolderMediaWithCropsModel) | ({
    mediaType: 'Image';
} & ImageMediaWithCropsModel) | ({
    mediaType: 'File';
} & FileMediaWithCropsModel) | ({
    mediaType: 'umbracoMediaVideo';
} & UmbracoMediaVideoMediaWithCropsModel) | ({
    mediaType: 'umbracoMediaAudio';
} & UmbracoMediaAudioMediaWithCropsModel) | ({
    mediaType: 'umbracoMediaArticle';
} & UmbracoMediaArticleMediaWithCropsModel) | ({
    mediaType: 'umbracoMediaVectorGraphics';
} & UmbracoMediaVectorGraphicsMediaWithCropsModel);

export type IApiMediaWithCropsResponseBaseModel = {
    path: null | string;
    createDate: string;
    updateDate: string;
    focalPoint?: ImageFocalPointModel;
    crops?: null | Array<ImageCropModel>;
    id: string;
    name: null | string;
    mediaType: null | string;
    url: null | string;
    extension?: null | string;
    width?: null | number;
    height?: null | number;
    bytes?: null | number;
    properties: null | {
        [key: string]: unknown;
    };
};

export type IApiMediaWithCropsResponseModel = ({
    mediaType: 'Folder';
} & FolderMediaWithCropsResponseModel) | ({
    mediaType: 'Image';
} & ImageMediaWithCropsResponseModel) | ({
    mediaType: 'File';
} & FileMediaWithCropsResponseModel) | ({
    mediaType: 'umbracoMediaVideo';
} & UmbracoMediaVideoMediaWithCropsResponseModel) | ({
    mediaType: 'umbracoMediaAudio';
} & UmbracoMediaAudioMediaWithCropsResponseModel) | ({
    mediaType: 'umbracoMediaArticle';
} & UmbracoMediaArticleMediaWithCropsResponseModel) | ({
    mediaType: 'umbracoMediaVectorGraphics';
} & UmbracoMediaVectorGraphicsMediaWithCropsResponseModel);

export type ImageCropCoordinatesModel = {
    x1: number;
    y1: number;
    x2: number;
    y2: number;
};

export type ImageCropModel = {
    alias: null | string;
    width: number;
    height: number;
    coordinates: ImageCropCoordinatesModel;
};

export type ImageFocalPointModel = {
    left: number;
    top: number;
};

export type ImageGalleryElementModel = IApiElementBaseModel & {
    contentType: 'imageGallery';
    properties?: ImageGalleryElementPropertiesModel;
};

export type ImageGalleryElementPropertiesModel = {
    gallery?: ApiBlockListModel | null;
};

export type ImageMediaPropertiesModel = {
    umbracoFile?: ApiImageCropperValueModel | null;
    umbracoWidth?: null | number;
    umbracoHeight?: null | number;
    umbracoBytes?: null | number;
    umbracoExtension?: null | string;
    altText?: null | string;
};

export type ImageMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
    mediaType: 'Image';
    properties?: ImageMediaPropertiesModel;
};

export type ImageMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & ImageMediaWithCropsModel;

export type ImageWithCaptionElementModel = IApiElementBaseModel & {
    contentType: 'imageWithCaption';
    properties?: ImageWithCaptionElementPropertiesModel;
};

export type ImageWithCaptionElementPropertiesModel = {
    image?: null | Array<IApiMediaWithCropsModel>;
    caption?: null | string;
};

export const LinkTypeModel = {
    CONTENT: 'Content',
    MEDIA: 'Media',
    EXTERNAL: 'External'
} as const;

export type LinkTypeModel = typeof LinkTypeModel[keyof typeof LinkTypeModel];

export type NowPageContentModel = IApiContentBaseModel & {
    contentType: 'nowPage';
    properties?: NowPageContentPropertiesModel;
};

export type NowPageContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel & {
    location?: null | string;
    upcoming?: ApiBlockListModel | null;
};

export type NowPageContentResponseModel = IApiContentResponseBaseModel & NowPageContentModel;

export type PageContentElementModel = IApiElementBaseModel & {
    contentType: 'pageContent';
    properties?: PageContentElementPropertiesModel;
};

export type PageContentElementPropertiesModel = {
    featuredImage?: null | Array<IApiMediaWithCropsModel>;
    title?: null | string;
    content?: null | string;
    grid?: ApiBlockGridModel | null;
};

export type PagedIApiContentResponseModel = {
    total: number;
    items: Array<IApiContentResponseModel>;
};

export type PagedIApiMediaWithCropsResponseModel = {
    total: number;
    items: Array<IApiMediaWithCropsResponseModel>;
};

export type PageSettingsElementModel = IApiElementBaseModel & {
    contentType: 'pageSettings';
    properties?: PageSettingsElementPropertiesModel;
};

export type PageSettingsElementPropertiesModel = {
    umbracoUrlName?: null | string;
    umbracoUrlAlias?: null | string;
    navigationTitle?: null | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type ProjectPostContentModel = IApiContentBaseModel & {
    contentType: 'projectPost';
    properties?: ProjectPostContentPropertiesModel;
};

export type ProjectPostContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel & {
    gitHubUrl?: null | Array<ApiLinkModel>;
    nuGetUrl?: null | Array<ApiLinkModel>;
};

export type ProjectPostContentResponseModel = IApiContentResponseBaseModel & ProjectPostContentModel;

export type ProjectsPageContentModel = IApiContentBaseModel & {
    contentType: 'projectsPage';
    properties?: ProjectsPageContentPropertiesModel;
};

export type ProjectsPageContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel;

export type ProjectsPageContentResponseModel = IApiContentResponseBaseModel & ProjectsPageContentModel;

export type RichTextElementModel = IApiElementBaseModel & {
    contentType: 'richText';
    properties?: RichTextElementPropertiesModel;
};

export type RichTextElementPropertiesModel = {
    content?: null | string;
};

export type SpeakingPageContentModel = IApiContentBaseModel & {
    contentType: 'speakingPage';
    properties?: SpeakingPageContentPropertiesModel;
};

export type SpeakingPageContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel;

export type SpeakingPageContentResponseModel = IApiContentResponseBaseModel & SpeakingPageContentModel;

export type SpeakingPostContentModel = IApiContentBaseModel & {
    contentType: 'speakingPost';
    properties?: SpeakingPostContentPropertiesModel;
};

export type SpeakingPostContentPropertiesModel = PageSettingsElementPropertiesModel & PageContentElementPropertiesModel & EventInfoElementPropertiesModel & {
    additionalEvents?: ApiBlockListModel | null;
};

export type SpeakingPostContentResponseModel = IApiContentResponseBaseModel & SpeakingPostContentModel;

export type UmbracoMediaArticleMediaPropertiesModel = {
    umbracoFile?: null | string;
    umbracoExtension?: null | string;
    umbracoBytes?: null | number;
};

export type UmbracoMediaArticleMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
    mediaType: 'umbracoMediaArticle';
    properties?: UmbracoMediaArticleMediaPropertiesModel;
};

export type UmbracoMediaArticleMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & UmbracoMediaArticleMediaWithCropsModel;

export type UmbracoMediaAudioMediaPropertiesModel = {
    umbracoFile?: null | string;
    umbracoExtension?: null | string;
    umbracoBytes?: null | number;
};

export type UmbracoMediaAudioMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
    mediaType: 'umbracoMediaAudio';
    properties?: UmbracoMediaAudioMediaPropertiesModel;
};

export type UmbracoMediaAudioMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & UmbracoMediaAudioMediaWithCropsModel;

export type UmbracoMediaVectorGraphicsMediaPropertiesModel = {
    umbracoFile?: null | string;
    umbracoExtension?: null | string;
    umbracoBytes?: null | number;
    umbracoWidth?: null | number;
    umbracoHeight?: null | number;
};

export type UmbracoMediaVectorGraphicsMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
    mediaType: 'umbracoMediaVectorGraphics';
    properties?: UmbracoMediaVectorGraphicsMediaPropertiesModel;
};

export type UmbracoMediaVectorGraphicsMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & UmbracoMediaVectorGraphicsMediaWithCropsModel;

export type UmbracoMediaVideoMediaPropertiesModel = {
    umbracoFile?: null | string;
    umbracoExtension?: null | string;
    umbracoBytes?: null | number;
};

export type UmbracoMediaVideoMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
    mediaType: 'umbracoMediaVideo';
    properties?: UmbracoMediaVideoMediaPropertiesModel;
};

export type UmbracoMediaVideoMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & UmbracoMediaVideoMediaWithCropsModel;

export type UpdateAlertElementModel = IApiElementBaseModel & {
    contentType: 'updateAlert';
    properties?: UpdateAlertElementPropertiesModel;
};

export type UpdateAlertElementPropertiesModel = {
    date?: null | string;
    content?: null | string;
};

export type YouTubeVideoElementModel = IApiElementBaseModel & {
    contentType: 'youTubeVideo';
    properties?: YouTubeVideoElementPropertiesModel;
};

export type YouTubeVideoElementPropertiesModel = {
    videoID?: null | string;
};

export type GetContent20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path?: never;
    query?: {
        /**
         * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fetch?: string;
        /**
         * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        filter?: Array<string>;
        /**
         * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        sort?: Array<string>;
        /**
         * Specifies the number of found content items to skip. Use this to control pagination of the response.
         */
        skip?: number;
        /**
         * Specifies the number of found content items to take. Use this to control pagination of the response.
         */
        take?: number;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content';
};

export type GetContent20Errors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContent20Error = GetContent20Errors[keyof GetContent20Errors];

export type GetContent20Responses = {
    /**
     * OK
     */
    200: PagedIApiContentResponseModel;
};

export type GetContent20Response = GetContent20Responses[keyof GetContent20Responses];

export type GetContentItemById20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path: {
        id: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/item/{id}';
};

export type GetContentItemById20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContentItemById20Responses = {
    /**
     * OK
     */
    200: IApiContentResponseModel;
};

export type GetContentItemById20Response = GetContentItemById20Responses[keyof GetContentItemById20Responses];

export type GetContentItemByPath20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path: {
        path: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/item/{path}';
};

export type GetContentItemByPath20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContentItemByPath20Responses = {
    /**
     * OK
     */
    200: IApiContentResponseModel;
};

export type GetContentItemByPath20Response = GetContentItemByPath20Responses[keyof GetContentItemByPath20Responses];

export type GetContentItems20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path?: never;
    query?: {
        id?: Array<string>;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/items';
};

export type GetContentItems20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetContentItems20Responses = {
    /**
     * OK
     */
    200: Array<IApiContentResponseModel>;
};

export type GetContentItems20Response = GetContentItems20Responses[keyof GetContentItems20Responses];

export type GetMedia20Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fetch?: string;
        /**
         * Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        filter?: Array<string>;
        /**
         * Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        sort?: Array<string>;
        /**
         * Specifies the number of found media items to skip. Use this to control pagination of the response.
         */
        skip?: number;
        /**
         * Specifies the number of found media items to take. Use this to control pagination of the response.
         */
        take?: number;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media';
};

export type GetMedia20Errors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetMedia20Error = GetMedia20Errors[keyof GetMedia20Errors];

export type GetMedia20Responses = {
    /**
     * OK
     */
    200: PagedIApiMediaWithCropsResponseModel;
};

export type GetMedia20Response = GetMedia20Responses[keyof GetMedia20Responses];

export type GetMediaItemById20Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/item/{id}';
};

export type GetMediaItemById20Errors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMediaItemById20Responses = {
    /**
     * OK
     */
    200: IApiMediaWithCropsResponseModel;
};

export type GetMediaItemById20Response = GetMediaItemById20Responses[keyof GetMediaItemById20Responses];

export type GetMediaItemByPath20Data = {
    body?: never;
    path: {
        path: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/item/{path}';
};

export type GetMediaItemByPath20Errors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMediaItemByPath20Responses = {
    /**
     * OK
     */
    200: IApiMediaWithCropsResponseModel;
};

export type GetMediaItemByPath20Response = GetMediaItemByPath20Responses[keyof GetMediaItemByPath20Responses];

export type GetMediaItems20Data = {
    body?: never;
    path?: never;
    query?: {
        id?: Array<string>;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/items';
};

export type GetMediaItems20Responses = {
    /**
     * OK
     */
    200: Array<IApiMediaWithCropsResponseModel>;
};

export type GetMediaItems20Response = GetMediaItems20Responses[keyof GetMediaItems20Responses];
