// Builds the site styles for BlockPreview in the Umbraco backend (../rick-butterfield),
// so block previews in the backoffice match the front end.
//
// BlockPreview loads stylesheets into each preview's shadow root with
// CSSStyleSheet.replaceSync(), so:
// - :root and body/html rules also need :host to apply inside the shadow root
// - @font-face doesn't work inside a shadow root, so fonts go in a separate
//   stylesheet that BackofficeFontLoader adds to the backoffice document
//
// Usage: npm run blockpreview:css [-- <path to UmbracoProject>]
import { compile } from 'sass';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const backend = path.resolve(root, process.argv[2] ?? '../rick-butterfield/src/UmbracoProject');
const wwwroot = path.join(backend, 'wwwroot');

const header = `/* Generated by rickbutterfield.dev/scripts/blockpreview-css.mjs. Do not edit; run \`npm run blockpreview:css\` in the frontend instead. */\n`;

const { css } = compile(path.join(root, 'src/styles/style.scss'), { style: 'expanded' });

const fontFaces = css.match(/@font-face\s*{[^}]*}/g) ?? [];
const styles = css
  .replace(/@font-face\s*{[^}]*}\s*/g, '')
  // Give the shadow root the same variables and base styles as the document
  .replace(/^:root \{/gm, ':root,\n:host {')
  .replace(/(^|,\s*)(html|body)(?=\s*[,{])/gm, '$1$2, :host');

await mkdir(path.join(wwwroot, 'css'), { recursive: true });
await writeFile(path.join(wwwroot, 'css/blockpreview.css'), header + styles);
await writeFile(path.join(wwwroot, 'css/blockpreview-fonts.css'), header + fontFaces.join('\n\n') + '\n');

// Copy the font files @font-face points at (/assets/fonts/...)
const fonts = [...new Set(fontFaces.flatMap((f) => [...f.matchAll(/url\(['"]?(\/assets\/fonts\/[^'")]+)/g)].map((m) => m[1])))];
await mkdir(path.join(wwwroot, 'assets/fonts'), { recursive: true });
for (const font of fonts) {
  await copyFile(path.join(root, 'public', font), path.join(wwwroot, font));
}

console.log(`Wrote blockpreview.css, blockpreview-fonts.css and ${fonts.length} fonts to ${wwwroot}`);
