/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlogsPagePropertiesModel } from './BlogsPagePropertiesModel';
import {
    BlogsPagePropertiesModelFromJSON,
    BlogsPagePropertiesModelFromJSONTyped,
    BlogsPagePropertiesModelToJSON,
} from './BlogsPagePropertiesModel';
import type { IApiContentModelBase } from './IApiContentModelBase';
import {
    IApiContentModelBaseFromJSON,
    IApiContentModelBaseFromJSONTyped,
    IApiContentModelBaseToJSON,
} from './IApiContentModelBase';

/**
 * 
 * @export
 * @interface BlogsPageContentModel
 */
export interface BlogsPageContentModel extends IApiContentModelBase {
    /**
     * 
     * @type {BlogsPagePropertiesModel}
     * @memberof BlogsPageContentModel
     */
    properties?: BlogsPagePropertiesModel;
}

/**
 * Check if a given object implements the BlogsPageContentModel interface.
 */
export function instanceOfBlogsPageContentModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlogsPageContentModelFromJSON(json: any): BlogsPageContentModel {
    return BlogsPageContentModelFromJSONTyped(json, false);
}

export function BlogsPageContentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogsPageContentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...IApiContentModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'properties': !exists(json, 'properties') ? undefined : BlogsPagePropertiesModelFromJSON(json['properties']),
    };
}

export function BlogsPageContentModelToJSON(value?: BlogsPageContentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiContentModelBaseToJSON(value),
        'properties': BlogsPagePropertiesModelToJSON(value.properties),
    };
}

