/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IApiContentResponseModelBase } from './IApiContentResponseModelBase';
import {
    IApiContentResponseModelBaseFromJSON,
    IApiContentResponseModelBaseFromJSONTyped,
    IApiContentResponseModelBaseToJSON,
} from './IApiContentResponseModelBase';

/**
 * 
 * @export
 * @interface BlogPostContentResponseModel
 */
export interface BlogPostContentResponseModel extends IApiContentResponseModelBase {
    /**
     * 
     * @type {string}
     * @memberof BlogPostContentResponseModel
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPostContentResponseModel
     */
    readonly contentType?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof BlogPostContentResponseModel
     */
    readonly properties?: { [key: string]: object; };
}

/**
 * Check if a given object implements the BlogPostContentResponseModel interface.
 */
export function instanceOfBlogPostContentResponseModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlogPostContentResponseModelFromJSON(json: any): BlogPostContentResponseModel {
    return BlogPostContentResponseModelFromJSONTyped(json, false);
}

export function BlogPostContentResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostContentResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...IApiContentResponseModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
    };
}

export function BlogPostContentResponseModelToJSON(value?: BlogPostContentResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiContentResponseModelBaseToJSON(value),
    };
}

