/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HttpValidationProblemDetails } from './HttpValidationProblemDetails';
import {
    instanceOfHttpValidationProblemDetails,
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsFromJSONTyped,
    HttpValidationProblemDetailsToJSON,
} from './HttpValidationProblemDetails';
import type { ProblemDetails } from './ProblemDetails';
import {
    instanceOfProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsFromJSONTyped,
    ProblemDetailsToJSON,
} from './ProblemDetails';

/**
 * @type GetContent400Response
 * 
 * @export
 */
export type GetContent400Response = HttpValidationProblemDetails | ProblemDetails;

export function GetContent400ResponseFromJSON(json: any): GetContent400Response {
    return GetContent400ResponseFromJSONTyped(json, false);
}

export function GetContent400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetContent400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...HttpValidationProblemDetailsFromJSONTyped(json, true), ...ProblemDetailsFromJSONTyped(json, true) };
}

export function GetContent400ResponseToJSON(value?: GetContent400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfHttpValidationProblemDetails(value)) {
        return HttpValidationProblemDetailsToJSON(value as HttpValidationProblemDetails);
    }
    if (instanceOfProblemDetails(value)) {
        return ProblemDetailsToJSON(value as ProblemDetails);
    }

    return {};
}

