/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HomePagePropertiesModel } from './HomePagePropertiesModel';
import {
    HomePagePropertiesModelFromJSON,
    HomePagePropertiesModelFromJSONTyped,
    HomePagePropertiesModelToJSON,
} from './HomePagePropertiesModel';
import type { IApiContentModelBase } from './IApiContentModelBase';
import {
    IApiContentModelBaseFromJSON,
    IApiContentModelBaseFromJSONTyped,
    IApiContentModelBaseToJSON,
} from './IApiContentModelBase';

/**
 * 
 * @export
 * @interface HomePageContentModel
 */
export interface HomePageContentModel extends IApiContentModelBase {
    /**
     * 
     * @type {HomePagePropertiesModel}
     * @memberof HomePageContentModel
     */
    properties?: HomePagePropertiesModel;
}

/**
 * Check if a given object implements the HomePageContentModel interface.
 */
export function instanceOfHomePageContentModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HomePageContentModelFromJSON(json: any): HomePageContentModel {
    return HomePageContentModelFromJSONTyped(json, false);
}

export function HomePageContentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): HomePageContentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...IApiContentModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'properties': !exists(json, 'properties') ? undefined : HomePagePropertiesModelFromJSON(json['properties']),
    };
}

export function HomePageContentModelToJSON(value?: HomePageContentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiContentModelBaseToJSON(value),
        'properties': HomePagePropertiesModelToJSON(value.properties),
    };
}

