/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlogPostContentModel } from './BlogPostContentModel';
import {
    instanceOfBlogPostContentModel,
    BlogPostContentModelFromJSON,
    BlogPostContentModelFromJSONTyped,
    BlogPostContentModelToJSON,
} from './BlogPostContentModel';
import type { BlogsPageContentModel } from './BlogsPageContentModel';
import {
    instanceOfBlogsPageContentModel,
    BlogsPageContentModelFromJSON,
    BlogsPageContentModelFromJSONTyped,
    BlogsPageContentModelToJSON,
} from './BlogsPageContentModel';
import type { ContentPageContentModel } from './ContentPageContentModel';
import {
    instanceOfContentPageContentModel,
    ContentPageContentModelFromJSON,
    ContentPageContentModelFromJSONTyped,
    ContentPageContentModelToJSON,
} from './ContentPageContentModel';
import type { HomePageContentModel } from './HomePageContentModel';
import {
    instanceOfHomePageContentModel,
    HomePageContentModelFromJSON,
    HomePageContentModelFromJSONTyped,
    HomePageContentModelToJSON,
} from './HomePageContentModel';

/**
 * @type IApiContentModel
 * 
 * @export
 */
export type IApiContentModel = BlogPostContentModel | BlogsPageContentModel | ContentPageContentModel | HomePageContentModel;

export function IApiContentModelFromJSON(json: any): IApiContentModel {
    return IApiContentModelFromJSONTyped(json, false);
}

export function IApiContentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IApiContentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BlogPostContentModelFromJSONTyped(json, true), ...BlogsPageContentModelFromJSONTyped(json, true), ...ContentPageContentModelFromJSONTyped(json, true), ...HomePageContentModelFromJSONTyped(json, true) };
}

export function IApiContentModelToJSON(value?: IApiContentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfBlogPostContentModel(value)) {
        return BlogPostContentModelToJSON(value as BlogPostContentModel);
    }
    if (instanceOfBlogsPageContentModel(value)) {
        return BlogsPageContentModelToJSON(value as BlogsPageContentModel);
    }
    if (instanceOfContentPageContentModel(value)) {
        return ContentPageContentModelToJSON(value as ContentPageContentModel);
    }
    if (instanceOfHomePageContentModel(value)) {
        return HomePageContentModelToJSON(value as HomePageContentModel);
    }

    return {};
}

