/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlogPostContentResponseModel } from './BlogPostContentResponseModel';
import {
    instanceOfBlogPostContentResponseModel,
    BlogPostContentResponseModelFromJSON,
    BlogPostContentResponseModelFromJSONTyped,
    BlogPostContentResponseModelToJSON,
} from './BlogPostContentResponseModel';
import type { BlogsPageContentResponseModel } from './BlogsPageContentResponseModel';
import {
    instanceOfBlogsPageContentResponseModel,
    BlogsPageContentResponseModelFromJSON,
    BlogsPageContentResponseModelFromJSONTyped,
    BlogsPageContentResponseModelToJSON,
} from './BlogsPageContentResponseModel';
import type { ContentPageContentResponseModel } from './ContentPageContentResponseModel';
import {
    instanceOfContentPageContentResponseModel,
    ContentPageContentResponseModelFromJSON,
    ContentPageContentResponseModelFromJSONTyped,
    ContentPageContentResponseModelToJSON,
} from './ContentPageContentResponseModel';
import type { HomePageContentResponseModel } from './HomePageContentResponseModel';
import {
    instanceOfHomePageContentResponseModel,
    HomePageContentResponseModelFromJSON,
    HomePageContentResponseModelFromJSONTyped,
    HomePageContentResponseModelToJSON,
} from './HomePageContentResponseModel';

/**
 * @type IApiContentResponseModel
 * 
 * @export
 */
export type IApiContentResponseModel = BlogPostContentResponseModel | BlogsPageContentResponseModel | ContentPageContentResponseModel | HomePageContentResponseModel;

export function IApiContentResponseModelFromJSON(json: any): IApiContentResponseModel {
    return IApiContentResponseModelFromJSONTyped(json, false);
}

export function IApiContentResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IApiContentResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BlogPostContentResponseModelFromJSONTyped(json, true), ...BlogsPageContentResponseModelFromJSONTyped(json, true), ...ContentPageContentResponseModelFromJSONTyped(json, true), ...HomePageContentResponseModelFromJSONTyped(json, true) };
}

export function IApiContentResponseModelToJSON(value?: IApiContentResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfBlogPostContentResponseModel(value)) {
        return BlogPostContentResponseModelToJSON(value as BlogPostContentResponseModel);
    }
    if (instanceOfBlogsPageContentResponseModel(value)) {
        return BlogsPageContentResponseModelToJSON(value as BlogsPageContentResponseModel);
    }
    if (instanceOfContentPageContentResponseModel(value)) {
        return ContentPageContentResponseModelToJSON(value as ContentPageContentResponseModel);
    }
    if (instanceOfHomePageContentResponseModel(value)) {
        return HomePageContentResponseModelToJSON(value as HomePageContentResponseModel);
    }

    return {};
}

