/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IApiContentModelBase } from './IApiContentModelBase';
import {
    IApiContentModelBaseFromJSON,
    IApiContentModelBaseFromJSONTyped,
    IApiContentModelBaseToJSON,
} from './IApiContentModelBase';
import type { IApiContentRouteModel } from './IApiContentRouteModel';
import {
    IApiContentRouteModelFromJSON,
    IApiContentRouteModelFromJSONTyped,
    IApiContentRouteModelToJSON,
} from './IApiContentRouteModel';

import {
     BlogPostContentResponseModelFromJSONTyped,
     BlogsPageContentResponseModelFromJSONTyped,
     ContentPageContentResponseModelFromJSONTyped,
     HomePageContentResponseModelFromJSONTyped
} from './index';

/**
 * 
 * @export
 * @interface IApiContentResponseModelBase
 */
export interface IApiContentResponseModelBase extends IApiContentModelBase {
    /**
     * 
     * @type {{ [key: string]: IApiContentRouteModel; }}
     * @memberof IApiContentResponseModelBase
     */
    readonly cultures?: { [key: string]: IApiContentRouteModel; };
    /**
     * 
     * @type {string}
     * @memberof IApiContentResponseModelBase
     */
    readonly name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IApiContentResponseModelBase
     */
    readonly createDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IApiContentResponseModelBase
     */
    readonly updateDate?: Date;
    /**
     * 
     * @type {IApiContentRouteModel}
     * @memberof IApiContentResponseModelBase
     */
    route?: IApiContentRouteModel;
    /**
     * 
     * @type {string}
     * @memberof IApiContentResponseModelBase
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof IApiContentResponseModelBase
     */
    readonly contentType?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IApiContentResponseModelBase
     */
    readonly properties?: { [key: string]: any; };
}

/**
 * Check if a given object implements the IApiContentResponseModelBase interface.
 */
export function instanceOfIApiContentResponseModelBase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IApiContentResponseModelBaseFromJSON(json: any): IApiContentResponseModelBase {
    return IApiContentResponseModelBaseFromJSONTyped(json, false);
}

export function IApiContentResponseModelBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IApiContentResponseModelBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['contentType'] === 'blogPost') {
            return BlogPostContentResponseModelFromJSONTyped(json, true);
        }
        if (json['contentType'] === 'blogsPage') {
            return BlogsPageContentResponseModelFromJSONTyped(json, true);
        }
        if (json['contentType'] === 'contentPage') {
            return ContentPageContentResponseModelFromJSONTyped(json, true);
        }
        if (json['contentType'] === 'homePage') {
            return HomePageContentResponseModelFromJSONTyped(json, true);
        }
    }
    return {
        ...IApiContentModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'cultures': !exists(json, 'cultures') ? undefined : (mapValues(json['cultures'], IApiContentRouteModelFromJSON)),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createDate': !exists(json, 'createDate') ? undefined : (new Date(json['createDate'])),
        'updateDate': !exists(json, 'updateDate') ? undefined : (new Date(json['updateDate'])),
        'route': !exists(json, 'route') ? undefined : IApiContentRouteModelFromJSON(json['route']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
    };
}

export function IApiContentResponseModelBaseToJSON(value?: IApiContentResponseModelBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiContentModelBaseToJSON(value),
        'route': IApiContentRouteModelToJSON(value.route),
    };
}

