/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ImageWithCaptionElementModel } from './ImageWithCaptionElementModel';
import {
    instanceOfImageWithCaptionElementModel,
    ImageWithCaptionElementModelFromJSON,
    ImageWithCaptionElementModelFromJSONTyped,
    ImageWithCaptionElementModelToJSON,
} from './ImageWithCaptionElementModel';
import type { PageContentElementModel } from './PageContentElementModel';
import {
    instanceOfPageContentElementModel,
    PageContentElementModelFromJSON,
    PageContentElementModelFromJSONTyped,
    PageContentElementModelToJSON,
} from './PageContentElementModel';
import type { PageSettingsElementModel } from './PageSettingsElementModel';
import {
    instanceOfPageSettingsElementModel,
    PageSettingsElementModelFromJSON,
    PageSettingsElementModelFromJSONTyped,
    PageSettingsElementModelToJSON,
} from './PageSettingsElementModel';
import type { RichTextElementModel } from './RichTextElementModel';
import {
    instanceOfRichTextElementModel,
    RichTextElementModelFromJSON,
    RichTextElementModelFromJSONTyped,
    RichTextElementModelToJSON,
} from './RichTextElementModel';

/**
 * @type IApiElementModel
 * 
 * @export
 */
export type IApiElementModel = ImageWithCaptionElementModel | PageContentElementModel | PageSettingsElementModel | RichTextElementModel;

export function IApiElementModelFromJSON(json: any): IApiElementModel {
    return IApiElementModelFromJSONTyped(json, false);
}

export function IApiElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IApiElementModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ImageWithCaptionElementModelFromJSONTyped(json, true), ...PageContentElementModelFromJSONTyped(json, true), ...PageSettingsElementModelFromJSONTyped(json, true), ...RichTextElementModelFromJSONTyped(json, true) };
}

export function IApiElementModelToJSON(value?: IApiElementModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfImageWithCaptionElementModel(value)) {
        return ImageWithCaptionElementModelToJSON(value as ImageWithCaptionElementModel);
    }
    if (instanceOfPageContentElementModel(value)) {
        return PageContentElementModelToJSON(value as PageContentElementModel);
    }
    if (instanceOfPageSettingsElementModel(value)) {
        return PageSettingsElementModelToJSON(value as PageSettingsElementModel);
    }
    if (instanceOfRichTextElementModel(value)) {
        return RichTextElementModelToJSON(value as RichTextElementModel);
    }

    return {};
}

