/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IApiElementModelBase } from './IApiElementModelBase';
import {
    IApiElementModelBaseFromJSON,
    IApiElementModelBaseFromJSONTyped,
    IApiElementModelBaseToJSON,
} from './IApiElementModelBase';
import type { ImageWithCaptionPropertiesModel } from './ImageWithCaptionPropertiesModel';
import {
    ImageWithCaptionPropertiesModelFromJSON,
    ImageWithCaptionPropertiesModelFromJSONTyped,
    ImageWithCaptionPropertiesModelToJSON,
} from './ImageWithCaptionPropertiesModel';

/**
 * 
 * @export
 * @interface ImageWithCaptionElementModel
 */
export interface ImageWithCaptionElementModel extends IApiElementModelBase {
    /**
     * 
     * @type {ImageWithCaptionPropertiesModel}
     * @memberof ImageWithCaptionElementModel
     */
    properties?: ImageWithCaptionPropertiesModel;
}

/**
 * Check if a given object implements the ImageWithCaptionElementModel interface.
 */
export function instanceOfImageWithCaptionElementModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageWithCaptionElementModelFromJSON(json: any): ImageWithCaptionElementModel {
    return ImageWithCaptionElementModelFromJSONTyped(json, false);
}

export function ImageWithCaptionElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageWithCaptionElementModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...IApiElementModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'properties': !exists(json, 'properties') ? undefined : ImageWithCaptionPropertiesModelFromJSON(json['properties']),
    };
}

export function ImageWithCaptionElementModelToJSON(value?: ImageWithCaptionElementModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiElementModelBaseToJSON(value),
        'properties': ImageWithCaptionPropertiesModelToJSON(value.properties),
    };
}

