/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageSettingsPropertiesModel
 */
export interface PageSettingsPropertiesModel {
    /**
     * 
     * @type {string}
     * @memberof PageSettingsPropertiesModel
     */
    umbracoUrlName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PageSettingsPropertiesModel
     */
    umbracoUrlAlias?: string | null;
}

/**
 * Check if a given object implements the PageSettingsPropertiesModel interface.
 */
export function instanceOfPageSettingsPropertiesModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageSettingsPropertiesModelFromJSON(json: any): PageSettingsPropertiesModel {
    return PageSettingsPropertiesModelFromJSONTyped(json, false);
}

export function PageSettingsPropertiesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageSettingsPropertiesModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'umbracoUrlName': !exists(json, 'umbracoUrlName') ? undefined : json['umbracoUrlName'],
        'umbracoUrlAlias': !exists(json, 'umbracoUrlAlias') ? undefined : json['umbracoUrlAlias'],
    };
}

export function PageSettingsPropertiesModelToJSON(value?: PageSettingsPropertiesModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'umbracoUrlName': value.umbracoUrlName,
        'umbracoUrlAlias': value.umbracoUrlAlias,
    };
}

