/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IApiElementModelBase } from './IApiElementModelBase';
import {
    IApiElementModelBaseFromJSON,
    IApiElementModelBaseFromJSONTyped,
    IApiElementModelBaseToJSON,
} from './IApiElementModelBase';
import type { PageSettingsPropertiesModel } from './PageSettingsPropertiesModel';
import {
    PageSettingsPropertiesModelFromJSON,
    PageSettingsPropertiesModelFromJSONTyped,
    PageSettingsPropertiesModelToJSON,
} from './PageSettingsPropertiesModel';

/**
 * 
 * @export
 * @interface PageSettingsElementModel
 */
export interface PageSettingsElementModel extends IApiElementModelBase {
    /**
     * 
     * @type {PageSettingsPropertiesModel}
     * @memberof PageSettingsElementModel
     */
    properties?: PageSettingsPropertiesModel;
}

/**
 * Check if a given object implements the PageSettingsElementModel interface.
 */
export function instanceOfPageSettingsElementModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageSettingsElementModelFromJSON(json: any): PageSettingsElementModel {
    return PageSettingsElementModelFromJSONTyped(json, false);
}

export function PageSettingsElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageSettingsElementModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...IApiElementModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'properties': !exists(json, 'properties') ? undefined : PageSettingsPropertiesModelFromJSON(json['properties']),
    };
}

export function PageSettingsElementModelToJSON(value?: PageSettingsElementModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiElementModelBaseToJSON(value),
        'properties': PageSettingsPropertiesModelToJSON(value.properties),
    };
}

