/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiBlockGridModel } from './ApiBlockGridModel';
import {
    ApiBlockGridModelFromJSON,
    ApiBlockGridModelFromJSONTyped,
    ApiBlockGridModelToJSON,
} from './ApiBlockGridModel';
import type { IApiMediaWithCropsModel } from './IApiMediaWithCropsModel';
import {
    IApiMediaWithCropsModelFromJSON,
    IApiMediaWithCropsModelFromJSONTyped,
    IApiMediaWithCropsModelToJSON,
} from './IApiMediaWithCropsModel';

/**
 * 
 * @export
 * @interface PageContentPropertiesModel
 */
export interface PageContentPropertiesModel {
    /**
     * 
     * @type {Array<IApiMediaWithCropsModel>}
     * @memberof PageContentPropertiesModel
     */
    featuredImage?: Array<IApiMediaWithCropsModel> | null;
    /**
     * 
     * @type {string}
     * @memberof PageContentPropertiesModel
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PageContentPropertiesModel
     */
    content?: string | null;
    /**
     * 
     * @type {ApiBlockGridModel}
     * @memberof PageContentPropertiesModel
     */
    grid?: ApiBlockGridModel;
}

/**
 * Check if a given object implements the PageContentPropertiesModel interface.
 */
export function instanceOfPageContentPropertiesModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageContentPropertiesModelFromJSON(json: any): PageContentPropertiesModel {
    return PageContentPropertiesModelFromJSONTyped(json, false);
}

export function PageContentPropertiesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageContentPropertiesModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'featuredImage': !exists(json, 'featuredImage') ? undefined : (json['featuredImage'] === null ? null : (json['featuredImage'] as Array<any>).map(IApiMediaWithCropsModelFromJSON)),
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'grid': !exists(json, 'grid') ? undefined : ApiBlockGridModelFromJSON(json['grid']),
    };
}

export function PageContentPropertiesModelToJSON(value?: PageContentPropertiesModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'featuredImage': value.featuredImage === undefined ? undefined : (value.featuredImage === null ? null : (value.featuredImage as Array<any>).map(IApiMediaWithCropsModelToJSON)),
        'title': value.title,
        'content': value.content,
        'grid': ApiBlockGridModelToJSON(value.grid),
    };
}

