/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IApiElementModelBase } from './IApiElementModelBase';
import {
    IApiElementModelBaseFromJSON,
    IApiElementModelBaseFromJSONTyped,
    IApiElementModelBaseToJSON,
} from './IApiElementModelBase';
import type { PageContentPropertiesModel } from './PageContentPropertiesModel';
import {
    PageContentPropertiesModelFromJSON,
    PageContentPropertiesModelFromJSONTyped,
    PageContentPropertiesModelToJSON,
} from './PageContentPropertiesModel';

/**
 * 
 * @export
 * @interface PageContentElementModel
 */
export interface PageContentElementModel extends IApiElementModelBase {
    /**
     * 
     * @type {PageContentPropertiesModel}
     * @memberof PageContentElementModel
     */
    properties?: PageContentPropertiesModel;
}

/**
 * Check if a given object implements the PageContentElementModel interface.
 */
export function instanceOfPageContentElementModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageContentElementModelFromJSON(json: any): PageContentElementModel {
    return PageContentElementModelFromJSONTyped(json, false);
}

export function PageContentElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageContentElementModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...IApiElementModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'properties': !exists(json, 'properties') ? undefined : PageContentPropertiesModelFromJSON(json['properties']),
    };
}

export function PageContentElementModelToJSON(value?: PageContentElementModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiElementModelBaseToJSON(value),
        'properties': PageContentPropertiesModelToJSON(value.properties),
    };
}

