/* tslint:disable */
/* eslint-disable */
/**
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IApiElementModelBase } from './IApiElementModelBase';
import {
    IApiElementModelBaseFromJSON,
    IApiElementModelBaseFromJSONTyped,
    IApiElementModelBaseToJSON,
} from './IApiElementModelBase';
import type { RichTextPropertiesModel } from './RichTextPropertiesModel';
import {
    RichTextPropertiesModelFromJSON,
    RichTextPropertiesModelFromJSONTyped,
    RichTextPropertiesModelToJSON,
} from './RichTextPropertiesModel';

/**
 * 
 * @export
 * @interface RichTextElementModel
 */
export interface RichTextElementModel extends IApiElementModelBase {
    /**
     * 
     * @type {RichTextPropertiesModel}
     * @memberof RichTextElementModel
     */
    properties?: RichTextPropertiesModel;
}

/**
 * Check if a given object implements the RichTextElementModel interface.
 */
export function instanceOfRichTextElementModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RichTextElementModelFromJSON(json: any): RichTextElementModel {
    return RichTextElementModelFromJSONTyped(json, false);
}

export function RichTextElementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichTextElementModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...IApiElementModelBaseFromJSONTyped(json, ignoreDiscriminator),
        'properties': !exists(json, 'properties') ? undefined : RichTextPropertiesModelFromJSON(json['properties']),
    };
}

export function RichTextElementModelToJSON(value?: RichTextElementModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...IApiElementModelBaseToJSON(value),
        'properties': RichTextPropertiesModelToJSON(value.properties),
    };
}

